#!/bin/sh

PKG_NAME="base-passwd"

# Fetch the source, install build dependencies and copy the control/changelog files.
prepare() {
	apt-get source "$PKG_NAME"
	apt-get build-dep "$PKG_NAME"
	cp control "$PKG_NAME"-*/debian/
	cp changelog "$PKG_NAME"-*/debian/
}

# Apply patches, if there are any.
do_patch() {
	for _file in patches/*.diff; do
		if [ -f "$_file" ]; then
			cd "$PKG_NAME"-* && \
				for _patch in ../patches/*.diff; do patch -p1 < "$_patch"; done && \
					cd ..
		fi
	done
}

# Build the package
do_build() {
	prepare
	do_patch
	cd "$PKG_NAME"-* && debuild -i -us -uc -b && cd ..
}

# Update package to new version
do_update() {
	prepare
	cd "$PKG_NAME"-* && dch -n && cd ..
	cp "$PKG_NAME"-*/debian/changelog .
	cp "$PKG_NAME"-*/debian/control .
	do_patch
	cd "$PKG_NAME"-* && debuild -i -us -uc -b && cd ..
}

# Clean the directory.
cleanup() {
	rm -rf "$PKG_NAME"-*
	for _file in "$PKG_NAME"_*; do rm "$_file"; done
}

case $1 in
	-c) cleanup ;;
	-u) do_update && cleanup ;;
	*) do_build && cleanup ;;
esac
