#!/bin/sh

# Self-explanatory
PKG="oksh"
VERSION="7.2"
PKG_NAME="$PKG"-"$VERSION"

# Build the package
do_build() {
	cd "$PKG_NAME" && debuild -i -us -uc -b && cd ..
}

cleanup() {
	cd "$PKG_NAME" && make clean && dh_clean && cd ..
	for _file in "$PKG"_*; do rm "$_file"; done
}

do_build
cleanup
